ALTER TABLE users ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD modified_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE categories MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE categories MODIFY modified_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products MODIFY modified_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders MODIFY modified_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_items MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE order_items MODIFY modified_at DATETIME DEFAULT CURRENT_TIMESTAMP;
