UPDATE products SET is_deleted = false WHERE is_deleted IS NULL;

ALTER TABLE products MODIFY modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE users MODIFY password VARCHAR(255) NOT NULL ;

ALTER TABLE users RENAME COLUMN roles TO role;